config/routes.rb
Rails.application.routes.draw do

  concern :commentable do
    resources :comments
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :questions do
    concerns :commentable
    resources :answers do
      post :accept, on: :member
    end
  end

  resources :answers, only: [], concerns: :commentable

  root 'questions#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities

    if user
      user.admin? ? admin_abilities : user_abilities(user)
    else
      guest_abilities
    end

  end

  def user_abilities(user)
    guest_abilities
    can :create, [Question, Answer, Comment]
    can :update, User, id: user.id
    can :destroy, User, id: user.id
    can :update, [Question, Answer, Comment], user_id: user.id
    can :destroy, [Question, Answer, Comment], user_id: user.id

    can :accept, Answer, question: {user_id: user.id}
  end

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question, counter_cache: true, touch: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :attachments, as: :attachmentable, dependent: :destroy
  validates :body, :user, :question, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  def accept
    answers = self.question.answers.where(accepted: true)
    if answers.count == 1 and answers.include?(self)
      return self
    end
    if answers.any?
      answers.map { |a| a.update!( accepted: false ) }
    end
    self.update!(accepted: true)

  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  mount_uploader :file, FileUploader

  belongs_to :user
  belongs_to :attachmentable, polymorphic: true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, :user, :commentable, presence: true
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates :provider, :uid, presence: true
  validates_uniqueness_of :uid, :scope => :provider
end

app/models/question.rb
class Question < ActiveRecord::Base

  acts_as_taggable

  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  belongs_to :user

	validates :title, :body, :user, presence: true
	validates_length_of		:title, in: 5..255

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :questions
  has_many :answers
  has_many :identities

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.find_for_oauth(auth)
    identity = Identity.where(auth.slice(:provider, :uid)).first
    return identity.user if identity

    email = auth.info ? auth.info.email : "tmp_#{auth.uid}_#{auth.provider}@localdomain.com"
    user = User.where(email: email).first_or_create! do |user|
      user.email = email
      user.password = Devise.friendly_token[0,20]
    end

    user.identities.create!( auth.slice(:provider, :uid) )
    user
  end

end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  respond_to :js
  actions :create, :update, :destroy
  before_action :authenticate_user!, only: [:create, :destroy]
  custom_actions resource: :accept
  belongs_to :question

  def accept
    resource.accept
  end

  protected

  def create_resource(object)
    object.user = current_user
    super
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  load_and_authorize_resource unless: :devise_controller?

  rescue_from CanCan::AccessDenied do
    render file: "#{Rails.root}/public/403.html", status: 403, layout: false
  end

end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_action :authenticate_user!, only: [:create, :update, :destroy]
  actions :create, :update, :destroy
  belongs_to :question, :answer, polymorphic: true
  respond_to :js

  protected

  def create_resource(object)
    object.user = current_user
    super
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"])

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linked_in].each do |provider|
    provides_callback_for provider
  end

end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  skip_load_and_authorize_resource :only => [:new, :create]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :build_answer, only: :show
  respond_to :html
  respond_to :js, only: :update
  actions :all, except: [:edit]

  protected

  def build_answer
    @answer = resource.answers.build
  end

  def create_resource(object)
    object.user = current_user
    super
  end

  def question_params
    params.require(:question).permit(:title, :body, :tag_list, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
div id="answer-#{resource.id}" class="#{ resource.accepted? ? 'accepted' : '' }"
  - if can? :accept, resource
    = link_to 'Best Answer', accept_question_answer_path(parent, resource), remote: true, method: :post

  p= resource.body
  p Attachments:
  ul
    - resource.attachments.each do |a|
      li= link_to a.file.identifier, a.file.url

  - if can? :update, resource
    = link_to 'Edit', "#EditAnswerForm#{resource.id}", data: {toggle: 'modal'}
    .modal.fade id="EditAnswerForm#{resource.id}" aria-hidden="true" aria-labelledby="EditAnswerFormLabel" role="dialog" tabindex="-1"
      .modal-dialog
        .modal-content
          .modal-header
            button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
            h4#EditAnswerFormLabel.modal-title Edit Answer #{resource.id}
          .modal-body
            = render 'answers/form', resource: resource, parent: parent, submit: 'Update Answer'
          .modal-footer
            button.btn.btn-default data-dismiss="modal" type="button"  Close

  - if can? :destroy, resource
    = ' | '
    = link_to 'Delete', question_answer_path(parent, resource), remote: true, method: :delete, data: {confirm: 'Are you sure?'}

  .comments-box
    = render 'comments/list', parent: resource

= subscribe_to "/answers/#{resource.id}/comments"

app/views/answers/_form.html.slim
- submit ||= 'Post Your Answer'
= simple_nested_form_for [parent, resource], remote: true do |f|
  = f.input :body, label: 'Your Answer'

  p Attachments:
  = f.simple_fields_for :attachments do |a|
    = a.input :file
    = a.link_to_remove "Remove this file"
  p= f.link_to_add "Add a file", :attachments

  p= f.button :submit, submit

app/views/answers/_list.html.slim
.subheader
  h3= pluralize parent.answers_count, 'Answer'
  hr
.answers-list
  - parent.answers.includes(:comments, :attachments).order(accepted: :desc, created_at: :asc).each do |answer|
    - if answer.persisted?
      = render 'answers/answer', resource: answer, parent: parent

app/views/answers/accept.js.erb
<% if resource.accepted? %>
  $('.answers').children('.accepted').removeClass('accepted');
  $('#answer-<%= resource.id %>').addClass('accepted');
  $('#answer-<%= resource.id %>').prependTo('.answers-list:first');
<% else %>
  $('#answer-<%= resource.id %>').removeClass('accepted')
<% end %>

app/views/answers/create.js.erb
<% if resource.errors.present? %>
  $('.new-answer-form').html('<%= j render 'form', submit: 'Post Your Answer' %>');
<% else %>
  $('.answers').html('<%= j render 'list' %>');
  $('.new-answer-form').html('<%= j render 'form', resource: parent.answers.build, submit: 'Post Your Answer' %>');
<% end %>

app/views/answers/destroy.js.erb
$("#answer-<%= resource.id%>").remove();

app/views/answers/update.js.erb
<% if resource.errors.present? %>
  $('form#edit_answer_<%= resource.id %>').html('<%= j render 'form', resource: resource, submit: 'Update Your Answer' %>');
<% else %>
  $('.answers').html('<%= j render 'list' %>');
  $('#EditAnswerForm<%= resource.id %>').modal('hide');
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
<% end %>

app/views/comments/_comment.html.slim
div id="comment-#{resource.id}"
  p= resource.body
  - if can? :update, resource
    = link_to 'Edit', "#EditCommentForm#{resource.id}", data: {toggle: 'modal'}
    .modal.fade id="EditCommentForm#{resource.id}" aria-hidden="true" aria-labelledby="EditCommentFormLabel" role="dialog" tabindex="-1"
      .modal-dialog
        .modal-content
          .modal-header
            button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
            h4#EditCommentFormLabel.modal-title Edit Comment #{resource.id}
          .modal-body
            = render 'comments/form', parent: parent, resource: resource, submit: 'Update Comment'
          .modal-footer
            button.btn.btn-default data-dismiss="modal" type="button"  Close
  - if can? :destroy, resource
    = ' | '
    = link_to 'Delete', polymorphic_path([parent, resource]), remote: true, method: :delete, data: {confirm: 'Are you sure?'}

app/views/comments/_form.html.slim
- submit ||= 'Post Your Comment'
= simple_form_for [parent, resource], remote: true do |f|
  = f.input :body, label: 'Your Comment'
  = f.button :submit, submit

app/views/comments/_list.html.slim
.comments-list
  - parent.comments.each do |comment|
    - if comment.persisted?
      = render 'comments/comment', parent: parent, resource: comment

- if can? :create, Comment
  .new-comment-form
    = render 'comments/form', parent: parent, resource: parent.comments.build

app/views/comments/create.js.erb
<% if parent_type == :question %>
  <% parent_selector = ".question .comments-box" %>
<% elsif parent_type == :answer %>
  <% parent_selector = "#answer-#{parent.id} .comments-box" %>
<% end %>

<% if resource.errors.present? %>
  $('<%= parent_selector %> .new-comment-form').html('<%= j render 'comments/form' %>');
<% else %>

  <% publish_to "/#{parent_type.to_s}s/#{parent.id}/comments" do %>
    $('<%= parent_selector %> .comments-list').append('<%= j render 'comments/comment' %>');
  <% end %>

  $('<%= parent_selector %> .new-comment-form').children('form')[0].reset();
<% end %>

app/views/comments/destroy.js.erb
$("#comment-<%= resource.id%>").remove();

app/views/comments/update.js.erb
<% if resource.errors.present? %>
$('form#edit_comment_<%= resource.id %>').html('<%= j render 'comments/form' %>');
<% else %>
$('<%= "#comment-#{resource.id}" %>').html('<%= j render 'comments/comment' %>');
$('#EditCommentForm<%= resource.id %>').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<% publish_to "/#{parent_type.to_s}s/#{parent.id}/comments" do %>
  $('<%= "#comment-#{resource.id}" %>').html('<%= j render 'comments/comment' %>');
<% end %>

<% end %>

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}")
      button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title LearnRoR
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

    .navbar.navbar-default.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          = link_to 'LearnRoR', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          ul.nav.navbar-nav
            li
              = link_to 'Link 1', '#'
            li
              = link_to 'Link 2', '#'
          ul.nav.navbar-nav.navbar-right
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#"
                | Dropdown
                b.caret
              ul.dropdown-menu
                - if current_user
                  li
                    = current_user.email
                  li
                    = link_to 'Logout' , destroy_user_session_path, method: :delete
                - else
                  li
                    = link_to 'Login', new_user_session_path

    .container
      .main
        .row
          .span9
            = render 'layouts/messages'
            = yield

app/views/questions/_answer_form.html.slim
= simple_form_for [@question, answer], remote: true do |f|
  = f.input :body, label: 'Your Answer'
  = f.button :submit, submit

app/views/questions/_form.html.slim
- remote ||= false
- submit ||= 'Post Your Question'
= simple_nested_form_for resource, remote: remote do |f|
  = f.input :title
  = f.input :body
  p Tags:
  = f.input :tag_list

  p Attachments:
  = f.simple_fields_for :attachments do |a|
    = a.input :file
    = a.link_to_remove "Remove this file"
  p= f.link_to_add "Add a file", :attachments

  .actions
    = f.button :submit, submit

app/views/questions/_question.html.slim
h3= resource.title
hr
p= resource.body

p Tags:
.tags-box
  - resource.tag_list.each do |tag|
    span.label.label-default= tag

p Attachments:
ul
  - resource.attachments.each do |a|
    li= link_to a.file.identifier, a.file.url

- if can? :update, resource
  = link_to 'Edit', '#EditQuestionForm', data: {toggle: 'modal'}
  #EditQuestionForm.modal.fade aria-hidden="true" aria-labelledby="EditQuestionFormLabel" role="dialog" tabindex="-1"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
          h4#EditQuestionFormLabel.modal-title Edit Question
        .modal-body
          = render partial: 'questions/form', locals: {submit: 'Update Question', remote: true}
        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Close

- if can? :destroy, resource
  = ' | '
  = link_to 'Delete', question_path(resource), method: :delete, data: {confirm: 'Are you sure?'}

.comments-box
  = render partial: 'comments/list', locals: {parent: resource}

app/views/questions/_question_form.html.slim
= simple_form_for @question, remote: true do |f|
  = f.input :title
  = f.input :body
  = f.button :submit, submit

app/views/questions/_questions_list.html.slim
div id="question-#{resource.id}"
  p= link_to resource.title, question_path(resource)

app/views/questions/index.html.slim
= link_to 'Ask a Question', new_question_path

.row
  .col-md-9
    .questions-box
      .subheader
        h3 Questions
      .questions-list
        - collection.each do |q|
          = render 'questions_list', resource: q

= subscribe_to "/questions"

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
.question id="question-#{resource.id}" data-question-id="#{resource.id}"
  = render 'question'


.answers
  = render 'answers/list', parent: resource

.new-answer-form
  - if can? :create, Answer
    = render 'answers/form', parent: resource, resource: @answer

= subscribe_to "/questions/#{resource.id}/comments"

app/views/questions/update.js.erb
<% if resource.errors.present? %>
$('form#edit_question_<%= resource.id %>').html('<%= j render 'form', submit: 'Update Question' %>');
<% else %>
$('.question').html('<%= j render 'question' %>');
$('#EditQuestionForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
<% end %>

app/views/shared/growl.js.erb
$.jGrowl("<p><%= j message.html_safe %></p>", {<%= options.join(', ').html_safe %>});